# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-24 14:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=256)),
                ('apellidos', models.CharField(max_length=256)),
                ('ficha', models.CharField(max_length=30)),
                ('puntaje', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Persona_Reto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.IntegerField()),
                ('nombre_grupo', models.CharField(max_length=50)),
                ('archivo', models.FileField(upload_to='respuestas')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Reto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=5000)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_publicacion', models.DateTimeField()),
                ('fecha_limite', models.DateTimeField()),
                ('tipo', models.CharField(max_length=50)),
                ('dificultad', models.CharField(choices=[('basico', 'Basico'), ('medio', 'Medio'), ('dificil', 'Dificil')], max_length=50)),
                ('archivo', models.FileField(upload_to='retos')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Categoria')),
            ],
        ),
        migrations.AddField(
            model_name='persona_reto',
            name='reto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Reto'),
        ),
    ]
