# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-20 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0002_auto_20170920_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_reto',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
