# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-14 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0003_auto_20170912_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
