# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-12 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0004_auto_20170912_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='identificacion',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
