# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-09-21 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0004_auto_20170921_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
