# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-24 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0005_auto_20170921_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_reto',
            name='calificacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persona_reto',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='retos.Persona'),
        ),
    ]
