# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-24 23:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0006_auto_20171024_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona_reto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
