# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-26 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0007_persona_reto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_reto',
            name='nombre_grupo',
            field=models.CharField(blank=True, default='individual', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='persona_reto',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='retos.Persona'),
        ),
    ]
