# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-10-26 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0008_auto_20171026_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona_reto',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
