# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0014_auto_20171106_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='autor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
