# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-23 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0015_reto_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='reto',
            name='puntos_maximos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
