# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-11-27 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0016_reto_puntos_maximos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='puntaje',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
