# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reto',
            name='tipo',
            field=models.CharField(choices=[('individual', 'Individual'), ('grupal', 'Grupal')], max_length=50),
        ),
    ]
